version: '3.9'

services:

  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog_platform
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:7
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  auth-service:
    build: ./services/auth-service
    container_name: auth_service
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - ./services/auth-service:/app
      - /app/node_modules
    env_file:
      - ./services/auth-service/.env
    depends_on:
      - postgres

  api-gateway:
    build: ./services/api-gateway
    container_name: api_gateway
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./services/api-gateway:/app
      - /app/node_modules
    env_file:
      - ./services/api-gateway/.env
    depends_on:
      - auth-service

  blog-service:
    build: ./services/blog-service
    container_name: blog_service
    restart: always
    ports:
      - "8002:8002"
    volumes:
      - ./services/blog-service:/app
      - /app/node_modules
    env_file:
      - ./services/blog-service/.env
    depends_on:
      - mongodb
      - rabbitmq
  
  notification-service:
    build: ./services/notification-service
    container_name: notification_service
    restart: always
    ports:
      - "8003:8003"
    volumes:
      - ./services/notification-service:/app
      - /app/node_modules
    env_file:
      - ./services/notification-service/.env
    depends_on:
      - mongodb
      - rabbitmq
  
  comment-service:
    build: ./services/comment-service
    container_name: comment_service
    restart: always
    ports:
      - "8004:8004"
    volumes:
      - ./services/comment-service:/app
      - /app/node_modules
    env_file:
      - ./services/comment-service/.env
    depends_on:
      - mongodb
      - rabbitmq

volumes:
  postgres_data:
  mongo_data: